filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/user-service/*.log
    fields:
      service: user-service

  - type: log
    enabled: true
    paths:
      - /logs/product-service/*.log
    fields:
      service: product-service

  - type: log
    enabled: true
    paths:
      - /logs/order-service/*.log
    fields:
      service: order-service

  - type: log
    enabled: true
    paths:
      - /logs/payment-service/*.log
    fields:
      service: payment-service

  - type: log
    enabled: true
    paths:
      - /logs/favourite-service/*.log
    fields:
      service: favourite-service

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5602"
