apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce-dev
data:
  environment: "development"
  log-level: "DEBUG"
  replicas: "1"