version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.14
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.14
    ports:
      - "5602:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

    filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.14
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/user-service:/logs/user-service
      - ./logs/product-service:/logs/product-service
      - ./logs/order-service:/logs/order-service
      - ./logs/payment-service:/logs/payment-service
      - ./logs/favourite-service:/logs/favourite-service
    depends_on:
      - logstash
    networks:
      - elk

networks:
  elk:
    driver: bridge
